# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 15:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),

    ]

    operations = [
        migrations.CreateModel(

            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(

            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),

                ('hostel', models.CharField(choices=[('C.V. Raman', 'C.V. Raman')], max_length=100)),
                ('action', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Action')),

            ],
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('N', 'Not read'), ('R', 'Read'), ('C', 'Complete')], default='N', max_length=1)),
                ('actions', models.ManyToManyField(to='main.Action')),

                ('categories', models.ManyToManyField(to='main.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),

                ('hostel', models.CharField(choices=[('C.V. Raman', 'C.V. Raman')], max_length=100)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='grievance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),

    ]
